import type { Metadata } from "next";
import { Toaster } from "sonner";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { TooltipProvider } from "@/components/ui/tooltip";

import { Reminder } from "@/components/misc";
import { Sidebar } from "@/components/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-primary/95 text-secondary`}
      >
        <div className="flex">
          <div className="sticky top-0 h-screen">
            <Sidebar />
          </div>
          <TooltipProvider>
            <div className="w-full p-4">{children}</div>
          </TooltipProvider>
        </div>

        <Toaster
          toastOptions={{
            classNames: {
              toast: "bg-primary!",
              title: "text-secondary!",
              description: "text-secondary/70!",
            },
          }}
        />
        <Reminder />
      </body>
    </html>
  );
}
