import type { Metadata } from "next";
import { Toaster } from "sonner";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { TooltipProvider } from "@/components/ui/tooltip";

import { Sidebar } from "@/components/sidebar";
import { DraggableWrapper, Reminder, ThemeProvider } from "@/components/misc";
import { TimeTracker, TimeTrackerProvider } from "@/components/timeTracker";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-secondary`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex bg-primary/95">
            <div className="sticky top-0 h-screen">
              <Sidebar />
            </div>

            <TooltipProvider>
              <TimeTrackerProvider>
                <div className="w-full p-4 ">{children}</div>
                <div className="fixed top-0 right-0 h-screen w-screen pointer-events-none">
                  <DraggableWrapper>
                    <div className="pointer-events-auto">
                      <TimeTracker draggable />
                    </div>
                  </DraggableWrapper>
                </div>
              </TimeTrackerProvider>
            </TooltipProvider>
          </div>

          <Toaster
            toastOptions={{
              classNames: {
                toast: "bg-primary!",
                title: "text-secondary!",
                description: "text-secondary/70!",
              },
            }}
          />

          <Reminder />
        </ThemeProvider>
      </body>
    </html>
  );
}
